name       : blinken
version    : 17.08.2
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/blinken-17.08.2.tar.xz : 501c74f2c45b1425d199da4c149451218b015106118c0f1caf14dc8cfbb246e3
license    : GPL-2.0
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
