name       : blinken
version    : 18.08.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/blinken-18.08.2.tar.xz : 6e8ebf55872262f694f8ebdf9ac396c064485bd4fee1477115f5ec6abc10a570
license    : GPL-2.0
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
