name       : blinken
version    : 16.12.0
release    : 1
source     :
    - http://download.kde.org/stable/applications/16.12.0/src/blinken-16.12.0.tar.xz : 9bf0187ca8df55d0bd1d4a4d55fa96b66ec0bd7d98ed9a521da1760da51b7450
license    : GPL-2.0
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
