name       : blinken
version    : 17.12.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/blinken-17.12.3.tar.xz : 20bfa6d3a3cc86f35fe885845c9909e99007b80f0744ecbe3c06c1c33d19aa51
license    : GPL-2.0
component  : games.action
optimize   : lto
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
