name       : blinken
version    : 21.08.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/blinken-21.08.0.tar.xz : 45288d7d4d7a03af621edd766fdb3bc8c86673cbaba2f42088778eb916d19844
homepage   : https://kde.org/applications/education/org.kde.blinken
license    : GPL-2.0-or-later
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
