name       : blinken
version    : 17.08.1
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/blinken-17.08.1.tar.xz : 189f55e1645fcfb03d3d8c56ddbdcce3fdd1c0b528d97a42a6df07ec35ac8ddb
license    : GPL-2.0
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges
    players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
