name       : blinken
version    : 17.12.2
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/blinken-17.12.2.tar.xz : e154ed3b3085a4a6e6476c44d9423173a3fbb1037ed5c62a697d94f246ae1701
license    : GPL-2.0
component  : games.action
optimize   : lto
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
