name       : blinken
version    : 18.12.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/blinken-18.12.0.tar.xz : 1d9e2be0939f1ad96eb7a4f9fb60c71f0d99fb3d4a7bf687c7ef28201e09d7b6
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
