name       : blinken
version    : 18.08.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/blinken-18.08.0.tar.xz : 750dfba8e2d6872d1730669c804fd41d29400d1760d18f32a890fdb78fd87747
license    : GPL-2.0
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
