name       : blinken
version    : 17.12.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/blinken-17.12.0.tar.xz : 59b1d063488f471c433521715a01bc4719949c9352a6ed6c32f1eea98ad95f36
license    : GPL-2.0
component  : games.action
optimize   : lto
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
