name       : blinken
version    : 17.04.0
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/blinken-17.04.0.tar.xz : 501c17347362eb406d8d9f4a718d30c4fbc4006092446a48eea537693cdb3556
license    : GPL-2.0
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
