name       : blinken
version    : 17.08.3
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/blinken-17.08.3.tar.xz : dd23a61b6a6639bad1c3b45ff9aaa444d0bd038413e5a03dc6368ee3b1d7d696
license    : GPL-2.0
component  : games.action
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
