name       : blinken
version    : 17.12.1
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/blinken-17.12.1.tar.xz : 8df1398d669699ae0ab53227941dae84e071f2bfd3cef0405e41a644987f6524
license    : GPL-2.0
component  : games.action
optimize   : lto
summary    : Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
description: |
    Blinken is based on an electronic game released in 1978, which challenges players to remember sequences of increasing length
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
